# Generated by Django 4.0.5 on 2022-07-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
