# Generated by Django 4.0.5 on 2023-01-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=20, null=True)),
                ('designation', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(max_length=20, null=True)),
                ('doj', models.DateField(null=True)),
                ('contact', models.IntegerField(null=True)),
            ],
        ),
    ]
