# Generated by Django 4.0.5 on 2023-01-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_rename_department_name_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
