# Generated by Django 4.0.5 on 2023-01-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_alter_department_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='DOJ',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Designation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Empname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
