# Generated by Django 4.0.5 on 2023-01-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_alter_employees_contact_alter_employees_doj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='DOJ',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Designation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Empname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Salary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
