# Generated by Django 4.0.5 on 2023-01-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0005_alter_employees_contact_alter_employees_doj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Salary',
            new_name='CTC',
        ),
    ]
